server:
  port: 80

app: 
  logging-to: console # options are: console / file
  drone: 
    video-ws-endpoint: /videofeed
    control-server-port: 1314
    video-server-port: 1313
    drone-id-length: 1 # Amount of symbols
    default-altitude: 4
    default-speed: 15


logging: 
  level:
    org.springframework: INFO
    com.odafa.cloudapp: DEBUG
    